[project]
site_name = "Raytrax"
site_url = "https://proximafusion.github.io/raytrax/"
repo_url = "https://github.com/proximafusion/raytrax"
docs_dir = "docs"
nav = [
    {"Home" = "index.md"},
    {"Usage" = [
        {"Get Started" = "getting-started.md"},
        {"Equilibrium" = "equilibrium.md"},
        {"Tuning" = "tuning.md"},
        {"Visualization" = [
            {"Overview" = "generated/gallery/index.md"},
            {"Radial profiles" = "generated/gallery/plot1d/plot_profiles.md"},
            {"Equilibrium visualisation" = "generated/gallery/plot2d/plot_equilibrium.md"},
            {"Beam trace visualisation" = "generated/gallery/plot2d/plot_beam_trace.md"},
            {"3D Visualisation" = "3d-visualisation.md"},
        ]},
    ]},
    {"Theory" = [
        {"Overview" = "theory.md"},
        {"Ray Tracing" = "theory/ray-tracing.md"},
        {"Absorption" = "theory/absorption.md"},
    ]},
    {"About" = [
        {"Limitations" = "limitations.md"},
        {"Acknowledgements" = "acknowledgements.md"},
    ]},
    {"Reference" = [
        {"API Reference" = "api.md"},
    ]},
]
extra_css = [
    "assets/extra.css",
]

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

[project.theme]
name = "zensical"
logo = "assets/proxima.svg"
favicon = "assets/proxima.svg"
palette.accent = "teal"
features = [
    "content.code.copy",
    "navigation.sections",
    "navigation.footer",
    "toc.follow",
    "navigation.indexes",
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
extensions = ["dataclasses"]

[project.markdown_extensions.toc]
toc_depth = 3


[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.footnotes]

[project.markdown_extensions."pymdownx.highlight"]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions."pymdownx.inlinehilite"]
[project.markdown_extensions."pymdownx.snippets"]
[project.markdown_extensions."pymdownx.superfences"]

[project.markdown_extensions."pymdownx.arithmatex"]
generic = true
